### ISSUE TITLE
Error changing default name of preview page

### ISSUE THREAD

**Issue by psugihara** [sofn-xyz/mailing#237]
**Describe the bug**

thanks for finding, @steven-tey

```
error - src/util/moduleManifestUtil.ts (19:36) @ getPreviewComponent
error - TypeError: previewModule[functionName] is not a function
    at getPreviewComponent (webpack-internal:///./src/util/moduleManifestUtil.ts:24:39)
    at getStaticProps (webpack-internal:///./src/pages/previews/[[...path]].tsx:51:104)
    at Object.renderToHTML (/Users/steventey/Desktop/dub/node_modules/next/server/render.tsx:749:20)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at doRender (/Users/steventey/Desktop/dub/node_modules/next/server/base-server.ts:1288:30)
    at cacheEntry.responseCache.get.isManualRevalidate.isManualRevalidate (/Users/steventey/Desktop/dub/node_modules/next/server/base-server.ts:1429:24)
    at /Users/steventey/Desktop/dub/node_modules/next/server/response-cache/index.ts:117:28 {
  page: '/previews/[[...path]]'
}
  17 |     [key: string]: () => ReactElement;
  18 |   } = previews[name as keyof typeof previews] as any;
> 19 |   return previewModule[functionName]();
     |                                    ^
  20 | }
  21 | 
  22 | export function getConfig(): MailingConfig {
```

**Expected behavior**
no errors :)

**Screenshots**

![CleanShot_2022-10-07_at_22 15 17](https://user-images.githubusercontent.com/282016/194686368-41994e88-6406-490c-a9dc-a69d9057a7a5.png)

**Comment by psugihara** [comment]
fixed in 0.8.3
