### ISSUE TITLE
Failed to load next.config.js 

### ISSUE THREAD

**Issue by SSardorf** [sofn-xyz/mailing#318]
**Describe the bug**
First time running `npx mailing` after installing causes the following error.
<img width="949" alt="image" src="https://user-images.githubusercontent.com/22572423/200573035-d5349913-8050-4115-bdfd-064b1492790a.png">

I definitely have a valid next.config.js

**To Reproduce**

1. install dependencies
2. run `npx mailing`

EDIT:
Note that I am running Next 12.3.0

**Comment by SSardorf** [comment]
Running `npx mailing preview` results in the following:

```
mailing starting preview server
mailing scanning for previews at ./emails/previews [
  'AccountCreated.tsx',
  'NewSignIn.tsx',
  'Reservation.tsx',
  'ResetPassword.tsx'
]
mailing linting templates in ./emails...
error - Failed to load next.config.js, see more info here https://nextjs.org/docs/messages/next-config-error
mailing preview

start the email preview server

Options:
  --version     Show version number                                    [boolean]
  --help        Show help                                              [boolean]
  --port        what port to start the preview server on         [default: 3883]
  --quiet       quiet mode (don't open browser after starting)
                                                      [boolean] [default: false]
  --emails-dir  the directory of your email templates      [default: "./emails"]

Error: Invalid value "automatic" in "--jsx=automatic"
    at /Users/ssardorf/dev/chain/marketing-site-v2/node_modules/esbuild/lib/main.js:1381:29
    at /Users/ssardorf/dev/chain/marketing-site-v2/node_modules/esbuild/lib/main.js:666:9
    at handleIncomingPacket (/Users/ssardorf/dev/chain/marketing-site-v2/node_modules/esbuild/lib/main.js:761:9)
    at Socket.readFromStdout (/Users/ssardorf/dev/chain/marketing-site-v2/node_modules/esbuild/lib/main.js:632:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
    ```

**Comment by SSardorf** [comment]
Doing `npm install esbuild` seems to have fixed this

**Comment by SSardorf** [comment]
> @SSardorf thanks for making an issue.
> 
> Any idea why esbuild wouldn't have been installed by installing mailing? It's a direct dependency of `mailing` so I'd think it should just get installed by npm. 😕

Not entirely sure why that would happen. Looking into it as well

**Comment by psugihara** [comment]
Closing for now, think we resolved the initial issue.
