### ISSUE TITLE
npx mailing run sever error

### ISSUE THREAD

**Issue by hehehai** [sofn-xyz/mailing#380]
**Describe the bug**
`npx mailing` error

**To Reproduce**

1. `pnpm add mailing-core`
2. `pnpm add -D mailing`
3. `npx mailing`
4. error not resolve miml-react, then i install `pnpm add mjml mjml-react`
5. `npx mailing` again got error

generator files successful, but server error

**Expected behavior**

**Screenshots**

```shell
✔ enter your email for occasional updates about mailing (optional) … 
mailing ok, no problem
mailing scanning for previews at ./emails/previews [
  'AccountCreated.tsx',
  'NewSignIn.tsx',
  'Reservation.tsx',
  'ResetPassword.tsx'
]
mailing linting templates in ./emails...
mailing starting preview server
event - compiled client and server successfully in 2.7s (322 modules)
mailing watching for changes to emails
mailing running preview at http://localhost:3883/
wait  - compiling / (client and server)...
wait  - compiling /_error (client and server)...
warn  - ../node_modules/.pnpm/registry.npmmirror.com+node-fetch@2.6.7/node_modules/node-fetch/lib/index.js
Module not found: Can't resolve 'encoding' in '/Users/guanwei/i/doit/my-course/node_modules/.pnpm/registry.npmmirror.com+node-fetch@2.6.7/node_modules/node-fetch/lib'
warn  - ../node_modules/.pnpm/registry.npmmirror.com+node-fetch@2.6.7/node_modules/node-fetch/lib/index.js
Module not found: Can't resolve 'encoding' in '/Users/guanwei/i/doit/my-course/node_modules/.pnpm/registry.npmmirror.com+node-fetch@2.6.7/node_modules/node-fetch/lib'
warn  - ../node_modules/.pnpm/registry.npmmirror.com+node-fetch@2.6.7/node_modules/node-fetch/lib/index.js
Module not found: Can't resolve 'encoding' in '/Users/guanwei/i/doit/my-course/node_modules/.pnpm/registry.npmmirror.com+node-fetch@2.6.7/node_modules/node-fetch/lib'
error - Error: ENOENT: no such file or directory, open '../node_modules/.pnpm/registry.npmmirror.com+uglify-js@3.17.4/node_modules/uglify-js/lib/utils.js'
    at Object.openSync (node:fs:599:3)
    at Object.readFileSync (node:fs:467:35)
    at eval (webpack-internal:///../node_modules/.pnpm/registry.npmmirror.com+uglify-js@3.17.4/node_modules/uglify-js/tools/node.js:20:19)
    at Array.map (<anonymous>)
    at eval (webpack-internal:///../node_modules/.pnpm/registry.npmmirror.com+uglify-js@3.17.4/node_modules/uglify-js/tools/node.js:19:30)
    at eval (webpack-internal:///../node_modules/.pnpm/registry.npmmirror.com+uglify-js@3.17.4/node_modules/uglify-js/tools/node.js:24:2)
    at Object.../node_modules/.pnpm/registry.npmmirror.com+uglify-js@3.17.4/node_modules/uglify-js/tools/node.js (webpack://mailing/node_modules/.pnpm/registry.npmmirror.com+@swc+helpers@0.4.11/node_modules/@swc/helpers/lib/_interop_require_wildcard.js?30d5:44:1)
    at __webpack_require__ (/Users/guanwei/i/doit/my-course/.mailing/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///../node_modules/.pnpm/registry.npmmirror.com+html-minifier@4.0.0/node_modules/html-minifier/src/htmlminifier.js:8:16)
    at Object.../node_modules/.pnpm/registry.npmmirror.com+html-minifier@4.0.0/node_modules/html-minifier/src/htmlminifier.js (webpack://mailing/node_modules/.pnpm/registry.npmmirror.com+@swc+helpers@0.4.11/node_modules/@swc/helpers/lib/_interop_require_wildcard.js?30d5:44:1) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '../node_modules/.pnpm/registry.npmmirror.com+uglify-js@3.17.4/node_modules/uglify-js/lib/utils.js',
  page: '/'
}
warn  - Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/basic-features/fast-refresh#how-it-works
mailing 500 / 4320ms
error - Error: ENOENT: no such file or directory, open '../node_modules/.pnpm/registry.npmmirror.com+uglify-js@3.17.4/node_modules/uglify-js/lib/utils.js'
    at Object.openSync (node:fs:599:3)
    at Object.readFileSync (node:fs:467:35)
    at eval (webpack-internal:///../node_modules/.pnpm/registry.npmmirror.com+uglify-js@3.17.4/node_modules/uglify-js/tools/node.js:20:19)
    at Array.map (<anonymous>)
    at eval (webpack-internal:///../node_modules/.pnpm/registry.npmmirror.com+uglify-js@3.17.4/node_modules/uglify-js/tools/node.js:19:30)
    at eval (webpack-internal:///../node_modules/.pnpm/registry.npmmirror.com+uglify-js@3.17.4/node_modules/uglify-js/tools/node.js:24:2)
    at Object.../node_modules/.pnpm/registry.npmmirror.com+uglify-js@3.17.4/node_modules/uglify-js/tools/node.js (webpack://mailing/node_modules/.pnpm/registry.npmmirror.com+@swc+helpers@0.4.11/node_modules/@swc/helpers/lib/_interop_require_wildcard.js?30d5:44:1)
    at __webpack_require__ (/Users/guanwei/i/doit/my-course/.mailing/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///../node_modules/.pnpm/registry.npmmirror.com+html-minifier@4.0.0/node_modules/html-minifier/src/htmlminifier.js:8:16)
    at Object.../node_modules/.pnpm/registry.npmmirror.com+html-minifier@4.0.0/node_modules/html-minifier/src/htmlminifier.js (webpack://mailing/node_modules/.pnpm/registry.npmmirror.com+@swc+helpers@0.4.11/node_modules/@swc/helpers/lib/_interop_require_wildcard.js?30d5:44:1) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '../node_modules/.pnpm/registry.npmmirror.com+uglify-js@3.17.4/node_modules/uglify-js/lib/utils.js',
  page: '/'
}
mailing 500 / 1045ms
mailing 200 /favicon.ico 6ms
mailing 200 /favicon.ico 4ms
```

**Desktop (please complete the following information):**
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64
    Binaries:
      Node: 18.9.0
      npm: 8.19.1
      Yarn: 1.22.19
      pnpm: 7.17.0
    Relevant packages:
      next: 12.3.2
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

**Additional context**

**Comment by alexfarrill** [comment]
@hehehai sorry if it was not clear, but Mailing does not currently support installation via pnpm.  npm and yarn 1.x are both supported.  I will update the docs to make that clearer and close this in favor of an issue describing the desired behavior -- "support install via pnpm".  That said, we'd love to get pnpm working -- pull requests welcome!  :)

**Comment by alexfarrill** [comment]
Closing in favor of https://github.com/sofn-xyz/mailing/issues/381  Pull requests welcome!
