### ISSUE TITLE
ReferenceError: sendMail2 is not defined after running npx mailing

### ISSUE THREAD

**Issue by DavidTParks** [sofn-xyz/mailing#469]
**Describe the bug**
After running `npx mailing` from the command line an unexpected error is thrown `ReferenceError: sendMail2 is not defined`

**To Reproduce**

1. Clone repository branch at https://github.com/DavidTParks/pixelfy/tree/bump-mailing
2. npm install
3. run npx mailing

**Expected behavior**
I'm expecting to see the mailing run dev gui pop up

**Screenshots**
<img width="1483" alt="Screenshot 2023-05-27 at 3 59 54 PM" src="https://github.com/sofn-xyz/mailing/assets/5482124/144efacc-37e0-45b4-8b14-60e4821d997c">

**Desktop (please complete the following information):**

- OS: MacOs
- Browser: Chrome
- Version: Version 113.0.5672.126
- 
**Additional context**
Happens on both version 1.0.0 and previous versions. It was working before, oddly. Not sure what is happening. 

full stack trace:

```
react-dom.development.js:29840 Download the React DevTools for a better development experience: https://reactjs.org/link/react-devtools
index.js:619 Uncaught ReferenceError: sendMail2 is not defined
    at eval (webpack://mailing/src/moduleManifest.js?3b50:376:1)
    at Module../src/moduleManifest.js (file:///Users/davidparks/Documents/Projects/pixelfy/.mailing/.next/server/pages/index.js:943:1)
    at __webpack_require__ (file:///Users/davidparks/Documents/Projects/pixelfy/.mailing/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///./src/util/moduleManifestUtil.ts:9:73)
    at Module../src/util/moduleManifestUtil.ts (file:///Users/davidparks/Documents/Projects/pixelfy/.mailing/.next/server/pages/index.js:965:1)
    at __webpack_require__ (file:///Users/davidparks/Documents/Projects/pixelfy/.mailing/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///./src/pages/index.tsx:6:82)
    at Module../src/pages/index.tsx (file:///Users/davidparks/Documents/Projects/pixelfy/.mailing/.next/server/pages/index.js:954:1)
    at __webpack_require__ (file:///Users/davidparks/Documents/Projects/pixelfy/.mailing/.next/server/webpack-runtime.js:33:43)
    at __webpack_exec__ (file:///Users/davidparks/Documents/Projects/pixelfy/.mailing/.next/server/pages/index.js:1734:39)
    at <anonymous> (file:///Users/davidparks/Documents/Projects/pixelfy/.mailing/.next/server/pages/index.js:1735:28)
    at Object.<anonymous> (file:///Users/davidparks/Documents/Projects/pixelfy/.mailing/.next/server/pages/index.js:1738:1)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._compile (file:///Users/davidparks/Documents/Projects/pixelfy/node_modules/esbuild-register/dist/node.js:2258:26)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Object.newLoader (file:///Users/davidparks/Documents/Projects/pixelfy/node_modules/esbuild-register/dist/node.js:2262:9)
    at extensions..js (file:///Users/davidparks/Documents/Projects/pixelfy/node_modules/esbuild-register/dist/node.js:4807:24)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at requirePage (file:///Users/davidparks/Documents/Projects/pixelfy/node_modules/next/src/server/require.ts:126:10)
    at <anonymous> (file:///Users/davidparks/Documents/Projects/pixelfy/node_modules/next/src/server/load-components.ts:105:16)
    at loadComponentsImpl (file:///Users/davidparks/Documents/Projects/pixelfy/node_modules/next/src/server/load-components.ts:104:24)
    at DevServer.findPageComponentsImpl (file:///Users/davidparks/Documents/Projects/pixelfy/node_modules/next/src/server/next-server.ts:1103:28)
    at DevServer.findPageComponents (file:///Users/davidparks/Documents/Projects/pixelfy/node_modules/next/src/server/dev/next-dev-server.ts:1789:14)
    at DevServer.renderPageComponent (file:///Users/davidparks/Documents/Projects/pixelfy/node_modules/next/src/server/base-server.ts:2109:20)
    at DevServer.renderToResponseImpl (file:///Users/davidparks/Documents/Projects/pixelfy/node_modules/next/src/server/base-server.ts:2164:24)
    at DevServer.pipeImpl (file:///Users/davidparks/Documents/Projects/pixelfy/node_modules/next/src/server/base-server.ts:1114:21)
    at Object.fn (file:///Users/davidparks/Documents/Projects/pixelfy/node_modules/next/src/server/next-server.ts:1585:11)
    at Router.execute (file:///Users/davidparks/Documents/Projects/pixelfy/node_modules/next/src/server/router.ts:503:24)
    at DevServer.runImpl (file:///Users/davidparks/Documents/Projects/pixelfy/node_modules/next/src/server/base-server.ts:1077:23)
    at DevServer.run (file:///Users/davidparks/Documents/Projects/pixelfy/node_modules/next/src/server/dev/next-dev-server.ts:1257:14)
    at DevServer.handleRequestImpl (file:///Users/davidparks/Documents/Projects/pixelfy/node_modules/next/src/server/base-server.ts:961:14)
:3883/__nextjs_original-stack-frame?isServer=true&isEdgeServer=false&errorMessage=ReferenceError%3A+sendMail2+is+not+defined&file=file%3A%2F%2F%2FUsers%2Fdavidparks%2FDocuments%2FProjects%2Fpixelfy%2F.mailing%2F.next%2Fserver%2Fpages%2Findex.js&methodName=Module..%2Fsrc%2FmoduleManifest.js&arguments=&lineNumber=943&column=1:1     Failed to load resource: the server responded with a status of 404 (Not Found)
:3883/__nextjs_original-stack-frame?isServer=true&isEdgeServer=false&errorMessage=ReferenceError%3A+sendMail2+is+not+defined&file=file%3A%2F%2F%2FUsers%2Fdavidparks%2FDocuments%2FProjects%2Fpixelfy%2F.mailing%2F.next%2Fserver%2Fwebpack-runtime.js&methodName=__webpack_require__&arguments=&lineNumber=33&column=43:1     Failed to load resource: the server responded with a status of 404 (Not Found)
:3883/__nextjs_original-stack-frame?isServer=true&isEdgeServer=false&errorMessage=ReferenceError%3A+sendMail2+is+not+defined&file=webpack-internal%3A%2F%2F%2F.%2Fsrc%2Futil%2FmoduleManifestUtil.ts&methodName=eval&arguments=&lineNumber=9&column=73:1     Failed to load resource: the server responded with a status of 404 (Not Found)
:3883/__nextjs_original-stack-frame?isServer=true&isEdgeServer=false&errorMessage=ReferenceError%3A+sendMail2+is+not+defined&file=file%3A%2F%2F%2FUsers%2Fdavidparks%2FDocuments%2FProjects%2Fpixelfy%2F.mailing%2F.next%2Fserver%2Fpages%2Findex.js&methodName=Module..%2Fsrc%2Futil%2FmoduleManifestUtil.ts&arguments=&lineNumber=965&column=1:1     Failed to load resource: the server responded with a status of 404 (Not Found)
:3883/__nextjs_original-stack-frame?isServer=true&isEdgeServer=false&errorMessage=ReferenceError%3A+sendMail2+is+not+defined&file=webpack-internal%3A%2F%2F%2F.%2Fsrc%2Fpages%2Findex.tsx&methodName=eval&arguments=&lineNumber=6&column=82:1     Failed to load resource: the server responded with a status of 404 (Not Found)
:3883/__nextjs_original-stack-frame?isServer=true&isEdgeServer=false&errorMessage=ReferenceError%3A+sendMail2+is+not+defined&file=file%3A%2F%2F%2FUsers%2Fdavidparks%2FDocuments%2FProjects%2Fpixelfy%2F.mailing%2F.next%2Fserver%2Fpages%2Findex.js&methodName=Module..%2Fsrc%2Fpages%2Findex.tsx&arguments=&lineNumber=954&column=1:1     Failed to load resource: the server responded with a status of 404 (Not Found)
:3883/__nextjs_original-stack-frame?isServer=true&isEdgeServer=false&errorMessage=ReferenceError%3A+sendMail2+is+not+defined&file=file%3A%2F%2F%2FUsers%2Fdavidparks%2FDocuments%2FProjects%2Fpixelfy%2F.mailing%2F.next%2Fserver%2Fpages%2Findex.js&methodName=__webpack_exec__&arguments=&lineNumber=1734&column=39:1     Failed to load resource: the server responded with a status of 404 (Not Found)
:3883/__nextjs_original-stack-frame?isServer=true&isEdgeServer=false&errorMessage=ReferenceError%3A+sendMail2+is+not+defined&file=file%3A%2F%2F%2FUsers%2Fdavidparks%2FDocuments%2FProjects%2Fpixelfy%2F.mailing%2F.next%2Fserver%2Fpages%2Findex.js&methodName=%3Canonymous%3E&arguments=&lineNumber=1735&column=28:1     Failed to load resource: the server responded with a status of 404 (Not Found)
:3883/__nextjs_original-stack-frame?isServer=true&isEdgeServer=false&errorMessage=ReferenceError%3A+sendMail2+is+not+defined&file=file%3A%2F%2F%2FUsers%2Fdavidparks%2FDocuments%2FProjects%2Fpixelfy%2F.mailing%2F.next%2Fserver%2Fpages%2Findex.js&methodName=Object.%3Canonymous%3E&arguments=&lineNumber=1738&column=1:1     Failed to load resource: the server responded with a status of 404 (Not Found)
:3883/__nextjs_original-stack-frame?isServer=true&isEdgeServer=false&errorMessage=ReferenceError%3A+sendMail2+is+not+defined&file=file%3A%2F%2F%2FUsers%2Fdavidparks%2FDocuments%2FProjects%2Fpixelfy%2Fnode_modules%2Fesbuild-register%2Fdist%2Fnode.js&methodName=Object.newLoader&arguments=&lineNumber=2262&column=9:1     Failed to load resource: the server responded with a status of 404 (Not Found)
:3883/__nextjs_original-stack-frame?isServer=true&isEdgeServer=false&errorMessage=ReferenceError%3A+sendMail2+is+not+defined&file=file%3A%2F%2F%2FUsers%2Fdavidparks%2FDocuments%2FProjects%2Fpixelfy%2Fnode_modules%2Fesbuild-register%2Fdist%2Fnode.js&methodName=extensions..js&arguments=&lineNumber=4807&column=24:1     Failed to load resource: the server responded with a status of 404 (Not Found)
:3883/__nextjs_original-stack-frame?isServer=true&isEdgeServer=false&errorMessage=ReferenceError%3A+sendMail2+is+not+defined&file=file%3A%2F%2F%2FUsers%2Fdavidparks%2FDocuments%2FProjects%2Fpixelfy%2Fnode_modules%2Fesbuild-register%2Fdist%2Fnode.js&methodName=Module._compile&arguments=&lineNumber=2258&column=26:1     Failed to load resource: the server responded with a status of 404 (Not Found)
:3883/__nextjs_original-stack-frame?isServer=true&isEdgeServer=false&errorMessage=ReferenceError%3A+sendMail2+is+not+defined&file=file%3A%2F%2F%2FUsers%2Fdavidparks%2FDocuments%2FProjects%2Fpixelfy%2Fnode_modules%2Fnext%2Fsrc%2Fserver%2Fload-components.ts&methodName=%3Canonymous%3E&arguments=&lineNumber=105&column=16:1     Failed to load resource: the server responded with a status of 404 (Not Found)
:3883/__nextjs_original-stack-frame?isServer=true&isEdgeServer=false&errorMessage=ReferenceError%3A+sendMail2+is+not+defined&file=file%3A%2F%2F%2FUsers%2Fdavidparks%2FDocuments%2FProjects%2Fpixelfy%2Fnode_modules%2Fnext%2Fsrc%2Fserver%2Fload-components.ts&methodName=loadComponentsImpl&arguments=&lineNumber=104&column=24:1     Failed to load resource: the server responded with a status of 404 (Not Found)
:3883/__nextjs_original-stack-frame?isServer=true&isEdgeServer=false&errorMessage=ReferenceError%3A+sendMail2+is+not+defined&file=file%3A%2F%2F%2FUsers%2Fdavidparks%2FDocuments%2FProjects%2Fpixelfy%2Fnode_modules%2Fnext%2Fsrc%2Fserver%2Frequire.ts&methodName=requirePage&arguments=&lineNumber=126&column=10:1     Failed to load resource: the server responded with a status of 404 (Not Found)
:3883/__nextjs_original-stack-frame?isServer=true&isEdgeServer=false&errorMessage=ReferenceError%3A+sendMail2+is+not+defined&file=file%3A%2F%2F%2FUsers%2Fdavidparks%2FDocuments%2FProjects%2Fpixelfy%2Fnode_modules%2Fnext%2Fsrc%2Fserver%2Fnext-server.ts&methodName=DevServer.findPageComponentsImpl&arguments=&lineNumber=1103&column=28:1     Failed to load resource: the server responded with a status of 404 (Not Found)
:3883/__nextjs_original-stack-frame?isServer=true&isEdgeServer=false&errorMessage=ReferenceError%3A+sendMail2+is+not+defined&file=file%3A%2F%2F%2FUsers%2Fdavidparks%2FDocuments%2FProjects%2Fpixelfy%2Fnode_modules%2Fnext%2Fsrc%2Fserver%2Fdev%2Fnext-dev-server.ts&methodName=DevServer.findPageComponents&arguments=&lineNumber=1789&column=14:1     Failed to load resource: the server responded with a status of 404 (Not Found)
:3883/__nextjs_original-stack-frame?isServer=true&isEdgeServer=false&errorMessage=ReferenceError%3A+sendMail2+is+not+defined&file=file%3A%2F%2F%2FUsers%2Fdavidparks%2FDocuments%2FProjects%2Fpixelfy%2Fnode_modules%2Fnext%2Fsrc%2Fserver%2Fbase-server.ts&methodName=DevServer.renderPageComponent&arguments=&lineNumber=2109&column=20:1     Failed to load resource: the server responded with a status of 404 (Not Found)
:3883/__nextjs_original-stack-frame?isServer=true&isEdgeServer=false&errorMessage=ReferenceError%3A+sendMail2+is+not+defined&file=file%3A%2F%2F%2FUsers%2Fdavidparks%2FDocuments%2FProjects%2Fpixelfy%2Fnode_modules%2Fnext%2Fsrc%2Fserver%2Fbase-server.ts&methodName=DevServer.renderToResponseImpl&arguments=&lineNumber=2164&column=24:1     Failed to load resource: the server responded with a status of 404 (Not Found)
:3883/__nextjs_original-stack-frame?isServer=true&isEdgeServer=false&errorMessage=ReferenceError%3A+sendMail2+is+not+defined&file=file%3A%2F%2F%2FUsers%2Fdavidparks%2FDocuments%2FProjects%2Fpixelfy%2Fnode_modules%2Fnext%2Fsrc%2Fserver%2Fbase-server.ts&methodName=DevServer.pipeImpl&arguments=&lineNumber=1114&column=21:1     Failed to load resource: the server responded with a status of 404 (Not Found)
:3883/__nextjs_original-stack-frame?isServer=true&isEdgeServer=false&errorMessage=ReferenceError%3A+sendMail2+is+not+defined&file=file%3A%2F%2F%2FUsers%2Fdavidparks%2FDocuments%2FProjects%2Fpixelfy%2Fnode_modules%2Fnext%2Fsrc%2Fserver%2Fnext-server.ts&methodName=Object.fn&arguments=&lineNumber=1585&column=11:1     Failed to load resource: the server responded with a status of 404 (Not Found)
:3883/__nextjs_original-stack-frame?isServer=true&isEdgeServer=false&errorMessage=ReferenceError%3A+sendMail2+is+not+defined&file=file%3A%2F%2F%2FUsers%2Fdavidparks%2FDocuments%2FProjects%2Fpixelfy%2Fnode_modules%2Fnext%2Fsrc%2Fserver%2Frouter.ts&methodName=Router.execute&arguments=&lineNumber=503&column=24:1     Failed to load resource: the server responded with a status of 404 (Not Found)
:3883/__nextjs_original-stack-frame?isServer=true&isEdgeServer=false&errorMessage=ReferenceError%3A+sendMail2+is+not+defined&file=file%3A%2F%2F%2FUsers%2Fdavidparks%2FDocuments%2FProjects%2Fpixelfy%2Fnode_modules%2Fnext%2Fsrc%2Fserver%2Fbase-server.ts&methodName=DevServer.runImpl&arguments=&lineNumber=1077&column=23:1     Failed to load resource: the server responded with a status of 404 (Not Found)
:3883/__nextjs_original-stack-frame?isServer=true&isEdgeServer=false&errorMessage=ReferenceError%3A+sendMail2+is+not+defined&file=file%3A%2F%2F%2FUsers%2Fdavidparks%2FDocuments%2FProjects%2Fpixelfy%2Fnode_modules%2Fnext%2Fsrc%2Fserver%2Fdev%2Fnext-dev-server.ts&methodName=DevServer.run&arguments=&lineNumber=1257&column=14:1     Failed to load resource: the server responded with a status of 404 (Not Found)
:3883/__nextjs_original-stack-frame?isServer=true&isEdgeServer=false&errorMessage=ReferenceError%3A+sendMail2+is+not+defined&file=file%3A%2F%2F%2FUsers%2Fdavidparks%2FDocuments%2FProjects%2Fpixelfy%2F.mailing%2F.next%2Fserver%2Fwebpack-runtime.js&methodName=__webpack_require__&arguments=&lineNumber=33&column=43:1     Failed to load resource: the server responded with a status of 404 (Not Found)
:3883/__nextjs_original-stack-frame?isServer=true&isEdgeServer=false&errorMessage=ReferenceError%3A+sendMail2+is+not+defined&file=file%3A%2F%2F%2FUsers%2Fdavidparks%2FDocuments%2FProjects%2Fpixelfy%2Fnode_modules%2Fnext%2Fsrc%2Fserver%2Fbase-server.ts&methodName=DevServer.handleRequestImpl&arguments=&lineNumber=961&column=14:1     Failed to load resource: the server responded with a status of 404 (Not Found)
:3883/__nextjs_original-stack-frame?isServer=true&isEdgeServer=false&errorMessage=ReferenceError%3A+sendMail2+is+not+defined&file=file%3A%2F%2F%2FUsers%2Fdavidparks%2FDocuments%2FProjects%2Fpixelfy%2F.mailing%2F.next%2Fserver%2Fwebpack-runtime.js&methodName=__webpack_require__&arguments=&lineNumber=33&column=43:1     Failed to load resource: the server responded with a status of 404 (Not Found)
DevTools failed to load source map: Could not load content for chrome-extension://bfnaelmomeimhlpmgjnjophhpkkoljpa/content-script/contentScript.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/browser-polyfill.js.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load source map: Could not load content for chrome-extension://bfnaelmomeimhlpmgjnjophhpkkoljpa/content-script/inpageSol.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
```

**Comment by DavidTParks** [comment]
Hey everybody, the issue was not including a default `sendMail` export in my config.

<img width="416" alt="Screenshot 2023-05-29 at 11 46 11 AM" src="https://github.com/sofn-xyz/mailing/assets/5482124/71421e9f-aa03-4277-95a3-de0035386b4c">

So adding `export default sendMail` to `emails/index.ts` did the trick.
